# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 643503ad9df616b5218eac68ac220380e1b354150314afff861c5073f92a494361375b5b88540d6189be6b660263115311701e833435971067ef244589be43c8

test:
  secret_key_base: 5c26de6e6dc71f06b003699588e87005be471420f2a9bbc82f6d8b8e430fa20f03b1658ba39e410002f6f62d75a56c89d656abad6fd924f6dccbfa0d7899e04f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
